"""Shared branding constants + helpers for every exported artifact.

Centralizes the `mgz-pkmn` mark, URL, and PDF metadata so the .xlsx and
the four PDF writers (binder, condensed, checklist, set-cards) agree on
how an exported file is signed. The PNG at `assets/logo.png` is the
rasterized version of the repo-root `assets/logo.svg` — regenerate with
`rsvg-convert -w 640 -h 160 assets/logo.svg -o src/mgz_pkmn/assets/logo.png`
when the source changes.
"""

from __future__ import annotations

import datetime as _dt
from importlib import resources
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from reportlab.pdfgen.canvas import Canvas

PROJECT_NAME = "mgz-pkmn"
PROJECT_URL = "https://mgz-pkmn.com"
PROJECT_AUTHOR = "mgz-pkmn"
PROJECT_CREATOR = f"mgz-pkmn ({PROJECT_URL})"

_LOGO_RESOURCE = "assets/logo.png"
LOGO_ASPECT = 320 / 80  # source SVG viewBox: w / h


def logo_path() -> Path:
    """Resolve the bundled PNG logo to a filesystem path."""
    return Path(str(resources.files("mgz_pkmn") / _LOGO_RESOURCE))


def apply_pdf_metadata(c: Canvas, title: str) -> None:
    """Stamp the canvas with Author / Creator / Title / Subject so the
    OS-level Get-Info pane names the project. Producer is left to
    ReportLab — overriding it requires private API and the public
    fields are what file-property viewers display."""
    c.setTitle(title)
    c.setAuthor(PROJECT_AUTHOR)
    c.setCreator(PROJECT_CREATOR)
    c.setSubject(f"Generated by {PROJECT_NAME}")
    c.setKeywords("pokemon, tcg, card-collection, mgz-pkmn")


def draw_pdf_footer(
    c: Canvas,
    page_size: tuple[float, float],
    page_num: int,
    generated_at: _dt.datetime | None = None,
) -> None:
    """Render the per-page branding footer: single 8 pt muted line with
    the project mark on the left, generated-at + URL centered, and the
    page number on the right. Sits at y=14 (about 0.2") so it never
    fights the content above."""
    page_w, _ = page_size
    margin = 24
    y = 14
    when = (generated_at or _dt.datetime.now()).strftime("%Y-%m-%d")
    c.saveState()
    c.setFont("Helvetica", 8)
    c.setFillColorRGB(0.55, 0.55, 0.55)
    c.drawString(margin, y, PROJECT_NAME)
    c.drawCentredString(page_w / 2, y, f"generated {when} · {PROJECT_URL}")
    c.drawRightString(page_w - margin, y, f"p.{page_num}")
    c.restoreState()


class PageTracker:
    """Wraps a `reportlab.pdfgen.canvas.Canvas` so each `show_page()` call
    stamps the branding footer first, and `finish()` stamps the footer on
    the final page before saving. Lets every PDF writer get per-page
    footers without duplicating the page-counting bookkeeping."""

    def __init__(self, c: Canvas, page_size: tuple[float, float]) -> None:
        self.c = c
        self.page_size = page_size
        self.page_num = 1
        self._generated_at = _dt.datetime.now()

    def show_page(self) -> None:
        draw_pdf_footer(self.c, self.page_size, self.page_num, self._generated_at)
        self.c.showPage()
        self.page_num += 1

    def finish(self) -> None:
        draw_pdf_footer(self.c, self.page_size, self.page_num, self._generated_at)
        self.c.save()


def draw_pdf_logo(c: Canvas, x: float, y: float, height: float) -> None:
    """Draw the rasterized logo with bottom-left at (x, y) and the given
    height in points. Width is derived from `LOGO_ASPECT`. Best-effort:
    if the bundled asset is missing or unreadable, we render nothing —
    the logo is decorative and a missing file shouldn't break the
    export."""
    width = height * LOGO_ASPECT
    try:
        from reportlab.lib.utils import ImageReader

        c.drawImage(
            ImageReader(str(logo_path())),
            x,
            y,
            width,
            height,
            preserveAspectRatio=True,
            mask="auto",
        )
    except Exception:
        return
