"""Shared branding constants + helpers for every exported artifact.

Centralizes the `mgz-pkmn` mark, URL, and PDF metadata so the .xlsx and
the four PDF writers (binder, condensed, checklist, set-cards) agree on
how an exported file is signed. Two PNG marks are bundled, both
rasterized from the repo-root SVGs preserving the 285x88 viewBox aspect
(regenerate when the source changes):

  rsvg-convert -w 640 assets/logo.svg      -o src/mgz_pkmn/assets/logo.png
  rsvg-convert -w 640 assets/logo-dark.svg -o src/mgz_pkmn/assets/logo-dark.png

`logo.png` is the dark-wordmark mark (for light backgrounds); the
`-dark` variant is the light wordmark that reads on the colored header
band the exports paint behind it.
"""

from __future__ import annotations

import datetime as _dt
import io
import sys
from importlib import resources
from typing import TYPE_CHECKING

from . import palette

if TYPE_CHECKING:
    from reportlab.pdfgen.canvas import Canvas

PROJECT_NAME = "mgz-pkmn"
PROJECT_URL = "https://mgz-pkmn.com"
PROJECT_AUTHOR = "mgz-pkmn"
PROJECT_CREATOR = f"mgz-pkmn ({PROJECT_URL})"

_LOGO_RESOURCES = {
    "on-light": "assets/logo.png",  # dark wordmark, for light backgrounds
    "on-dark": "assets/logo-dark.png",  # light wordmark, for the colored band
}
LOGO_ASPECT = 285 / 88  # source SVG viewBox: w / h

# Tropical header band the exports paint wherever the logo sits, so the
# light-wordmark mark reads. Deep frond green (palm-600) from the design
# tokens — the in-brand successor to the old dark-slate band. Matches the
# section-header band in the binder + checklist writers so the logo blends
# with those headers rather than introducing a third shade.
HEADER_PANEL_RGB = palette.rgb01(palette.HEADER_BAND)

_logo_bytes_cache: dict[str, bytes] = {}
_logo_warned = False


def logo_bytes(variant: str = "on-light") -> bytes:
    """Read a bundled PNG logo mark as raw bytes.

    `variant` is `"on-light"` (dark wordmark, default) or `"on-dark"`
    (light wordmark for the colored header band). Goes through
    `importlib.resources.files(...).read_bytes()` so the asset resolves
    whether the package is installed from a wheel, a zipimport, or a
    source checkout (no on-disk path assumption). Results are cached per
    variant for the life of the process — the files are small (<15 KB)
    and get touched on every export."""
    if variant not in _logo_bytes_cache:
        resource = _LOGO_RESOURCES[variant]
        _logo_bytes_cache[variant] = (resources.files("mgz_pkmn") / resource).read_bytes()
    return _logo_bytes_cache[variant]


def apply_pdf_metadata(c: Canvas, title: str) -> None:
    """Stamp the canvas with Author / Creator / Title / Subject so the
    OS-level Get-Info pane names the project. Producer is left to
    ReportLab — overriding it requires private API and the public
    fields are what file-property viewers display."""
    c.setTitle(title)
    c.setAuthor(PROJECT_AUTHOR)
    c.setCreator(PROJECT_CREATOR)
    c.setSubject(f"Generated by {PROJECT_NAME}")
    c.setKeywords("pokemon, tcg, card-collection, mgz-pkmn")


def draw_pdf_footer(
    c: Canvas,
    page_size: tuple[float, float],
    page_num: int,
    generated_at: _dt.datetime | None = None,
) -> None:
    """Render the per-page branding footer: single 8 pt muted line with
    the project mark on the left, generated-at + URL centered, and the
    page number on the right. Sits at y=14 (about 0.2") so it never
    fights the content above."""
    page_w, _ = page_size
    margin = 24
    y = 14
    when = (generated_at or _dt.datetime.now()).strftime("%Y-%m-%d")
    c.saveState()
    c.setFont("Helvetica", 8)
    c.setFillColorRGB(*palette.rgb01("fg-3"))
    c.drawString(margin, y, PROJECT_NAME)
    c.drawCentredString(page_w / 2, y, f"generated {when} · {PROJECT_URL}")
    c.drawRightString(page_w - margin, y, f"p.{page_num}")
    c.restoreState()


class PageTracker:
    """Wraps a `reportlab.pdfgen.canvas.Canvas` so each `show_page()` call
    stamps the branding footer first, and `finish()` stamps the footer on
    the final page before saving. Lets every PDF writer get per-page
    footers without duplicating the page-counting bookkeeping."""

    def __init__(self, c: Canvas, page_size: tuple[float, float]) -> None:
        self.c = c
        self.page_size = page_size
        self.page_num = 1
        self._generated_at = _dt.datetime.now()

    def show_page(self) -> None:
        draw_pdf_footer(self.c, self.page_size, self.page_num, self._generated_at)
        self.c.showPage()
        self.page_num += 1

    def finish(self) -> None:
        draw_pdf_footer(self.c, self.page_size, self.page_num, self._generated_at)
        self.c.save()


def draw_pdf_logo(
    c: Canvas, x: float, y: float, height: float, *, draw_panel: bool = False
) -> None:
    """Draw the rasterized logo with bottom-left at (x, y) and the given
    height in points. Width is derived from `LOGO_ASPECT`.

    Draws the light-wordmark mark, which reads on the colored header
    band. `draw_panel=True` paints that band behind the logo on
    otherwise-white pages (set-cards layout); callers that already place
    the logo inside an existing header band leave this `False`.

    Failures fetching or decoding the bundled asset are logged to
    stderr once per process; the export proceeds without a logo so a
    bad asset doesn't break the file. Programming errors (wrong types,
    canvas in a bad state) are re-raised."""
    width = height * LOGO_ASPECT
    try:
        data = logo_bytes("on-dark")
    except (FileNotFoundError, OSError, ModuleNotFoundError) as exc:
        _warn_once(f"logo asset unavailable: {exc}")
        return

    if draw_panel:
        pad = max(2.0, height * 0.25)
        c.saveState()
        c.setFillColorRGB(*HEADER_PANEL_RGB)
        c.rect(x - pad, y - pad, width + 2 * pad, height + 2 * pad, fill=1, stroke=0)
        c.restoreState()

    from reportlab.lib.utils import ImageReader

    try:
        reader = ImageReader(io.BytesIO(data))
    except OSError as exc:  # corrupted/unreadable PNG bytes
        _warn_once(f"logo decode failed: {exc}")
        return
    c.drawImage(
        reader,
        x,
        y,
        width,
        height,
        preserveAspectRatio=True,
        mask="auto",
    )


def _warn_once(msg: str) -> None:
    """One-shot stderr warning so a broken asset doesn't spam the log."""
    global _logo_warned
    if _logo_warned:
        return
    _logo_warned = True
    print(f"  ! branding: {msg}", file=sys.stderr)
