services:
  - type: web
    name: mgz-pkmn
    runtime: docker
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: POKEMONTCG_IO_API_KEY
        sync: false
